CREATE TABLE person (id INTEGER PRIMARY KEY,name VARCHAR,conj_form INTEGER,UNIQUE(name));
INSERT INTO person (name,conj_form) VALUES ('yo',1);
INSERT INTO person (name,conj_form) VALUES ('tú',2);
INSERT INTO person (name,conj_form) VALUES ('él',3);
INSERT INTO person (name,conj_form) VALUES ('ella',3);
INSERT INTO person (name,conj_form) VALUES ('usted',3);
INSERT INTO person (name,conj_form) VALUES ('nosotros',4);
INSERT INTO person (name,conj_form) VALUES ('vosotros',5);
INSERT INTO person (name,conj_form) VALUES ('ellos',6);
INSERT INTO person (name,conj_form) VALUES ('ellas',6);
INSERT INTO person (name,conj_form) VALUES ('ustedes',6);
